

// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   tutorialSidebar: [
//     'intro',
//     {
//       type: 'category',
//       label: 'Modules',
//       items: [
//         {
//           type: 'category',
//           label: 'Module 1: The Robotic Nervous System (ROS 2)',
//           items: [
//             'module-1-ros2/ros2-basics',
//             'module-1-ros2/module-1-intro',
//             'module-1-ros2/nodes-topics-services',
//           ],
//         },
//         {
//           type: 'category',
//           label: 'Module 2: Digital Twin Simulation',
//           items: [
//             'module-2-digital-twin/introduction',
//             'module-2-digital-twin/digital-twin-concept',
//             'module-2-digital-twin/physics-simulation',
//           ],
//         },
//         {
//           type: 'category',
//           label: 'Module 3: Simulation and Advanced Navigation',
//           items: [
//             'module-3-isaac-brain/isaac-sim-ros-overview',
//           ],
//         },
//         {
//           type: 'category',
//           label: 'Module 4: Vision-Language-Action (VLA)',
//           items: [
//             'module-4-vla/introduction-to-vla',
//             'module-4-vla/synthetic-data-generation',
//             'module-4-vla/whisper-voice-to-action',
//           ],
//         },
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Tutorial - Basics',
//       items: [
//         'tutorial-basics/create-a-document',
//         'tutorial-basics/create-a-blog-post',
//         'tutorial-basics/create-a-page',
//         'tutorial-basics/markdown-features',
//         'tutorial-basics/deploy-your-site',
//         'tutorial-basics/congratulations',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Tutorial - Extras',
//       items: [
//         'tutorial-extras/manage-docs-versions',
//         'tutorial-extras/translate-your-site',
//       ],
//     },
//   ],
// };

// export default sidebars;


















import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          link: {
            type: 'doc',
            id: 'module-1-ros2/module-1-intro',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'module-1-ros2', // picks up all files in this folder automatically
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twin Simulation',
          link: {
            type: 'doc',
            id: 'module-2-digital-twin/introduction',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'module-2-digital-twin',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 3: Simulation and Advanced Navigation',
          link: {
            type: 'doc',
            id: 'module-3-isaac-brain/isaac-sim-ros-overview',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'module-3-isaac-brain',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module  Module 4: Vision-Language-Action (VLA)',
          link: {
            type: 'doc',
            id: 'module-4-vla/introduction-to-vla',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'module-4-vla',
            },
          ],
        },
      ],
    },

    // Optional: keep the default Docusaurus tutorials or remove them if not needed
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/create-a-page',
        'tutorial-basics/markdown-features',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/congratulations',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
  ],
};

export default sidebars;